name: 'TomChv'
description: 'A test for a github action'
author: 'Vasek'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
